### ISSUE TITLE
ValueError: dict contains fields not in fieldnames: 'oa_works_count'

### ISSUE THREAD

**Issue by yuch25** [ourresearch/openalex-documentation-scripts#2]
openalex-snapshot/data/authors/updated_date=2023-04-02/part_000.gz
openalex-snapshot/data/authors/updated_date=2023-04-11/part_000.gz
Traceback (most recent call last):
  File "/mnt/e/OpenAlex/openalex-snapshot-20230503/flatten-openalex-jsonl_authors.py", line 685, in <module>
    flatten_authors()
  File "/mnt/e/OpenAlex/openalex-snapshot-20230503/flatten-openalex-jsonl_authors.py", line 251, in flatten_authors
    counts_by_year_writer.writerow(count_by_year)
  File "/home/yuc/anaconda3/lib/python3.10/csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
  File "/home/yuc/anaconda3/lib/python3.10/csv.py", line 149, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'oa_works_count'

**Comment by myanesp** [comment]
Same here. Have you been able to manage and solve it?

**Comment by yuch25** [comment]
> Same here. Have you been able to manage and solve it?

I just deleted the code relevent to "oa_works_count", because I don't need it.

**Comment by J0nasW** [comment]
I also came across this issue. I added the 'oa_works_count' field to the csv_files dict in line 30. This has solved the error.

```
'counts_by_year': {
            'name': os.path.join(CSV_DIR, 'authors_counts_by_year.csv.gz'),
            'columns': [
                'author_id', 'year', 'works_count', 'cited_by_count', 'oa_works_count'
            ]
        }
```

**Comment by caseydm** [comment]
This should be fixed now!
